---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migrator-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  # Set the size of the PVC to 100Gi
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: migrator
  name: migrator
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrator
  template:
    metadata:
      labels:
        app: migrator
    spec:
      containers:
      - name: app-migrator-container
        image: alpine
        resources: {}
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        env:
          - name: PGPASSWORD
            value: password
        args:
          - "-c"
          - |
            apk add postgresql-client
            sleep infinity
        volumeMounts:
        - name: data
          mountPath: /data  # Mount path for the PVC
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: migrator-pvc  # Name of the PVC to be created
